spring.application.name=tripnest-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/tripnest
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B59
jwt.expiration=86400000

weather.api.key=${WEATHER_API_KEY:YOUR_OPENWEATHER_API_KEY}
weather.api.url=https://api.openweathermap.org/data/2.5/weather

google.places.api.key=${GOOGLE_PLACES_API_KEY:YOUR_GOOGLE_PLACES_API_KEY}
google.places.api.url=https://maps.googleapis.com/maps/api/place/textsearch/json
